# Generated by Django 4.0.2 on 2026-02-22 22:04

from django.db import migrations


def drop_seatalloc_train_index_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    table_name = 'app_seatallocation'
    index_name = 'seatalloc_train_idx'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(1)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND index_name = %s
            """,
            [table_name, index_name],
        )
        exists = bool(cursor.fetchone()[0])

    if exists:
        schema_editor.execute(f"DROP INDEX `{index_name}` ON `{table_name}`")


def cleanup_smsdeliverylog_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    table_name = 'app_smsdeliverylog'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(1)
            FROM information_schema.tables
            WHERE table_schema = DATABASE()
              AND table_name = %s
            """,
            [table_name],
        )
        table_exists = bool(cursor.fetchone()[0])

    if not table_exists:
        return

    with schema_editor.connection.cursor() as cursor:
        # Drop FK constraints that reference booking_id/payment_id if they exist.
        cursor.execute(
            """
            SELECT constraint_name
            FROM information_schema.key_column_usage
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND referenced_table_name IS NOT NULL
              AND column_name IN ('booking_id', 'payment_id')
            """,
            [table_name],
        )
        fk_names = [row[0] for row in cursor.fetchall()]

        for fk_name in fk_names:
            schema_editor.execute(f"ALTER TABLE `{table_name}` DROP FOREIGN KEY `{fk_name}`")

        # Drop columns only if present.
        for col in ('booking_id', 'payment_id'):
            cursor.execute(
                """
                SELECT COUNT(1)
                FROM information_schema.columns
                WHERE table_schema = DATABASE()
                  AND table_name = %s
                  AND column_name = %s
                """,
                [table_name, col],
            )
            col_exists = bool(cursor.fetchone()[0])
            if col_exists:
                schema_editor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{col}`")

    # Final model removal in DB layer.
    schema_editor.execute(f"DROP TABLE IF EXISTS `{table_name}`")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_classtype_adult_price_child_price'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(cleanup_smsdeliverylog_if_exists, migrations.RunPython.noop),
                migrations.RunPython(drop_seatalloc_train_index_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='smsdeliverylog',
                    name='booking',
                ),
                migrations.RemoveField(
                    model_name='smsdeliverylog',
                    name='payment',
                ),
                migrations.RemoveIndex(
                    model_name='seatallocation',
                    name='seatalloc_train_idx',
                ),
                migrations.DeleteModel(
                    name='SMSDeliveryLog',
                ),
            ],
        ),
    ]
