# Generated by Django 4.0.2 on 2026-02-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_smsdeliverylog_booking_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS app_smsdeliverylog CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
